--insert into answers(answer, created_on, modified_on) values('333300', now(), now());
--insert into answers(answer, created_on, modified_on) values('207', now(), now());
--insert into answers(answer, created_on, modified_on) values('CORRECT FOR ALL', now(), now());
--insert into answers(answer, created_on, modified_on) values('1200', now(), now());
--insert into answers(answer, created_on, modified_on) values('50', now(), now());
--insert into answers(answer, created_on, modified_on) values('249', now(), now());
--insert into answers(answer, created_on, modified_on) values('16', now(), now());
--insert into answers(answer, created_on, modified_on) values('20', now(), now());
--insert into answers(answer, created_on, modified_on) values('12', now(), now());
--insert into answers(answer, created_on, modified_on) values('150', now(), now());
--insert into answers(answer, created_on, modified_on) values('xxxxx11', now(), now());
--insert into answers(answer, created_on, modified_on) values('xxxxx12', now(), now());

insert into answers(answer, created_on, modified_on) values('11Answer1', now(), now());
insert into answers(answer, created_on, modified_on) values('22Answer2', now(), now());
insert into answers(answer, created_on, modified_on) values('33Answer3', now(), now());
insert into answers(answer, created_on, modified_on) values('44Answer4', now(), now());
insert into answers(answer, created_on, modified_on) values('55Answer', now(), now());
insert into answers(answer, created_on, modified_on) values('Answer66', now(), now());
insert into answers(answer, created_on, modified_on) values('Answer77', now(), now());
insert into answers(answer, created_on, modified_on) values('Answer88', now(), now());
insert into answers(answer, created_on, modified_on) values('Answer99', now(), now());
insert into answers(answer, created_on, modified_on) values('Answer00', now(), now());
